blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion / Questions
    url: https://github.com/TanaTTV/Discord-Archiver/discussions
    about: Ask questions and get help from the community
